version: '3.8'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8100:80
    volumes:
      - ./:/var/www/html/

  db_api: 
    image: mysql
    restart: unless-stopped
    container_name: db_api
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 30s
      interval: 2s
      retries: 30

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: pma_api
    ports:
      - 8020:80
    depends_on:
      db_api:
        condition: service_healthy
    environment:
      - PMA_HOST=db_api
      - PMA_ARBITRARY=1